# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chocbomb"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["glejeune"]
  s.date = "2011-12-05"
  s.description = "ChocBomb is a shameful copy of ChocTop - Build and deploy tools for Cocoa apps using Sparkle for distributions and upgrades; it\342\200\231s like Hoe but for Cocoa apps."
  s.email = "gregoire.lejeune@gmail.com"
  s.executables = ["chocbomb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/chocbomb",
    "chocbomb.gemspec",
    "lib/chocbomb.rb",
    "lib/chocbomb/rake/tasks.rb",
    "lib/chocbomb/tool.rb",
    "lib/chocbomb/tools/dmg.rb",
    "lib/chocbomb/tools/feed.rb",
    "lib/chocbomb/tools/images.rb",
    "lib/chocbomb/tools/xcode.rb",
    "templates/Rakefile.erb",
    "templates/default_background.jpg",
    "templates/default_volume.icns",
    "test/helper.rb",
    "test/ressources/default_background.jpg",
    "test/ressources/default_background.png",
    "test/test_chocbomb.rb"
  ]
  s.homepage = "http://github.com/glejeune/chocbomb"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "ChocBomb is a shameful copy of ChocTop"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<plist>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<escape>, [">= 0.0.4"])
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 4.2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<plist>, [">= 3.1.0"])
      s.add_dependency(%q<escape>, [">= 0.0.4"])
      s.add_dependency(%q<builder>, [">= 2.1.2"])
      s.add_dependency(%q<RedCloth>, [">= 4.2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<plist>, [">= 3.1.0"])
    s.add_dependency(%q<escape>, [">= 0.0.4"])
    s.add_dependency(%q<builder>, [">= 2.1.2"])
    s.add_dependency(%q<RedCloth>, [">= 4.2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

